<?php

namespace Batna\AlerteBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * SeuilRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SeuilRepository extends EntityRepository
{
}