ctxt:
    pattern:  /
    defaults: { _controller: "BatnaArchiBundle:Contexte:index" }

ctxt_show:
    pattern:  /{id}/show
    defaults: { _controller: "BatnaArchiBundle:Contexte:show" }

ctxt_new:
    pattern:  /new
    defaults: { _controller: "BatnaArchiBundle:Contexte:new" }

ctxt_create:
    pattern:  /create
    defaults: { _controller: "BatnaArchiBundle:Contexte:create" }
    requirements: { _method: post }

ctxt_edit:
    pattern:  /{id}/edit
    defaults: { _controller: "BatnaArchiBundle:Contexte:edit" }

ctxt_update:
    pattern:  /{id}/update
    defaults: { _controller: "BatnaArchiBundle:Contexte:update" }
    requirements: { _method: post }

ctxt_delete:
    pattern:  /{id}/delete
    defaults: { _controller: "BatnaArchiBundle:Contexte:delete" }
    requirements: { _method: post }

varCon:
    pattern:  /var/
    defaults: { _controller: "BatnaArchiBundle:Variable:indexCon" }

varCon_show:
    pattern:  /var/{id}/show
    defaults: { _controller: "BatnaArchiBundle:Variable:showCon" }

varCon_new:
    pattern:  /var/new
    defaults: { _controller: "BatnaArchiBundle:Variable:newCon" }

varCon_create:
    pattern:  /var/create
    defaults: { _controller: "BatnaArchiBundle:Variable:createCon" }
    requirements: { _method: post }

varCon_edit:
    pattern:  /var/{id}/edit
    defaults: { _controller: "BatnaArchiBundle:Variable:editCon" }

varCon_update:
    pattern:  /var/{id}/update
    defaults: { _controller: "BatnaArchiBundle:Variable:updateCon" }
    requirements: { _method: post }

varCon_delete:
    pattern:  /var/{id}/delete
    defaults: { _controller: "BatnaArchiBundle:Variable:deleteCon" }
    requirements: { _method: post }

varValCon_edit:
    pattern:  /{con}/var/{var}/edit
    defaults: { _controller: "BatnaArchiBundle:Variable:editValCon" }

varValCon_update:
    pattern:  /{con}/var/{var}/update
    defaults: { _controller: "BatnaArchiBundle:Variable:updateValCon" }
    requirements: { _method: post }

varValCon_delete:
    pattern:  /{con}/var/{var}/delete
    defaults: { _controller: "BatnaArchiBundle:Variable:deleteValCon" }
    requirements: { _method: post }