BatnaArchiBundle_ctxt:
        resource: "@BatnaArchiBundle/Resources/config/routing/contexte.yml"
        prefix:   /ctxt

BatnaArchiBundle_env:
        resource: "@BatnaArchiBundle/Resources/config/routing/environnement.yml"
        prefix:   /env

BatnaArchiBundle_host:
        resource: "@BatnaArchiBundle/Resources/config/routing/host.yml"
        prefix:   /host