#!/bin/bash

cd /home/sentenza/workspace/Monitoring

sudo rm -rf app/cache/dev
rm -rf app/logs/dev.log

php app/console cache:clear
php app/console doctrine:database:drop --force
php app/console doctrine:database:create
php app/console doctrine:schema:create
#php app/console doctrine:fixtures:load

mysql --user=root monitoring < fixtures.sql

sudo rm -rf app/cache/dev
rm -rf app/logs/dev.log