<?php

namespace Batna\SiebelBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * EnterpriseRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EnterpriseRepository extends EntityRepository
{
}