<?php

namespace Batna\SiebelBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * GatewayRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GatewayRepository extends EntityRepository
{
}