BatnaToolsBundle:
    resource: "@BatnaToolsBundle/Resources/config/routing.yml"
    prefix:   /

BatnaAlerteBundle:
    resource: "@BatnaAlerteBundle/Resources/config/routing.yml"
    prefix:   /

BatnaSiebelBundle:
    resource: "@BatnaSiebelBundle/Resources/config/routing.yml"
    prefix:   /

BatnaArchiBundle:
    resource: "@BatnaArchiBundle/Resources/config/routing.yml"
    prefix:   /

fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

fos_user_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix: /profile

fos_user_register:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix: /register

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /resetting

fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /profile

FOS_user_group:
    resource: "@BatnaUserBundle/Resources/config/routing/group.yml"
    prefix: /group
    
Batna_User:
    resource: "@BatnaUserBundle/Resources/config/routing.yml"
    prefix:   /