parameters:
#    batna_tools.example.class: Batna\ToolsBundle\Example

services:
#    batna_tools.example:
#        class: %batna_tools.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
