user:
    pattern:  /
    defaults: { _controller: "BatnaUserBundle:User:index" }

user_show:
    pattern:  /{id}/show
    defaults: { _controller: "BatnaUserBundle:User:show" }

user_new:
    pattern:  /new
    defaults: { _controller: "BatnaUserBundle:User:new" }

user_create:
    pattern:  /create
    defaults: { _controller: "BatnaUserBundle:User:create" }
    requirements: { _method: post }

user_edit:
    pattern:  /{id}/edit
    defaults: { _controller: "BatnaUserBundle:User:edit" }

user_update:
    pattern:  /{id}/update
    defaults: { _controller: "BatnaUserBundle:User:update" }
    requirements: { _method: post }

user_delete:
    pattern:  /{id}/delete
    defaults: { _controller: "BatnaUserBundle:User:delete" }
    requirements: { _method: post }

user_add_role:
    pattern:  /{id}/role/add
    defaults: { _controller: "BatnaUserBundle:User:addRole" }
    requirements: { _method: post }

user_add_group:
    pattern:  /{id}/group/add
    defaults: { _controller: "BatnaUserBundle:User:addGroup" }
    requirements: { _method: post }

user_remove_role:
    pattern:  /{id}/role/remove
    defaults: { _controller: "BatnaUserBundle:User:removeRole" }
    requirements: { _method: post }

user_remove_group:
    pattern:  /{id}/group/remove
    defaults: { _controller: "BatnaUserBundle:User:removeGroup" }
    requirements: { _method: post }