<?php

namespace Batna\ArchiBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ContexteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ContexteRepository extends EntityRepository
{
}