<?php

namespace Batna\ArchiBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ValVarEnvironnementRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ValVarEnvironnementRepository extends EntityRepository
{
}