parameters:
#    batna_siebel.example.class: Batna\SiebelBundle\Example

services:
#    batna_siebel.example:
#        class: %batna_siebel.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
