BatnaUserBundle_user:
    resource: "@BatnaUserBundle/Resources/config/routing/user.yml"
    prefix:   /user

BatnaUserBundle_group:
    resource: "@BatnaUserBundle/Resources/config/routing/group.yml"
    prefix:   /group

BatnaUserBundle_homepage:
    pattern:  /
    defaults: { _controller: "BatnaUserBundle:Dashboard:index" }

